id: IC438B91F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T11:45:00+00:00'
last_modified: '2022-06-07T12:09:05.750593+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23151
  title: གསུང་འབུམ། བློ་བཟང་ཚུལ་ཁྲིམས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    1E09:
      image_group_id: I1KG8795
      title: Volume 1 of gsung 'bum/_blo bzang tshul khrims/
      total_pages: 714
      order: 1
      base_file: 1E09.txt
    '3717':
      image_group_id: I1KG8796
      title: Volume 2 of gsung 'bum/_blo bzang tshul khrims/
      total_pages: 801
      order: 2
      base_file: 3717.txt
    CE44:
      image_group_id: I1KG8797
      title: Volume 3 of gsung 'bum/_blo bzang tshul khrims/
      total_pages: 700
      order: 3
      base_file: CE44.txt
    5EB8:
      image_group_id: I1KG8798
      title: Volume 4 of gsung 'bum/_blo bzang tshul khrims/
      total_pages: 656
      order: 4
      base_file: 5EB8.txt
    AA99:
      image_group_id: I1KG8799
      title: Volume 5 of gsung 'bum/_blo bzang tshul khrims/
      total_pages: 647
      order: 5
      base_file: AA99.txt
    '0641':
      image_group_id: I1KG8800
      title: Volume 6 of gsung 'bum/_blo bzang tshul khrims/
      total_pages: 657
      order: 6
      base_file: 0641.txt
    BF97:
      image_group_id: I1KG8801
      title: Volume 7 of gsung 'bum/_blo bzang tshul khrims/
      total_pages: 612
      order: 7
      base_file: BF97.txt
    A385:
      image_group_id: I1KG8802
      title: Volume 8 of gsung 'bum/_blo bzang tshul khrims/
      total_pages: 700
      order: 8
      base_file: A385.txt
    E274:
      image_group_id: I1KG8803
      title: Volume 9 of gsung 'bum/_blo bzang tshul khrims/
      total_pages: 454
      order: 9
      base_file: E274.txt
    13F4:
      image_group_id: I1KG8804
      title: Volume 10 of gsung 'bum/_blo bzang tshul khrims/
      total_pages: 553
      order: 10
      base_file: 13F4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
